### ISSUE TITLE
Beta release todo list

### ISSUE THREAD

**Issue by jackcallister** [jarsbe/worsley#1]
- [x] Use an object for action handler registration 
- [ ] Add error messages for common instantiation mistakes
- [ ] Add error messages for common container usage mistakes
- [ ] Verify container doesn't export React
- [ ] Assess difficulty of supporting ES5 with constructor functions
- [x] Ensure unique constants
- [ ] Stringify worsley#load
